[package]
name = "reader"
version = "0.1.0-alpha.4"
description = "A local-first reading library"
authors = ["Nouraldin Farge"]
license = "MIT"
repository = "https://github.com/NouraldinFarge/Reader"
edition = "2021"

[lib]
name = "reader_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-single-instance = "2"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
